name: Publish Docker image to GitHub Container Registry

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: "https://githubaction.azurecr.io/"
  REGISTRY_OWNER: githubaction
  REGISTRY_NAME: githubaction
  IMAGE_NAME: nodejs-azure

jobs:

  build:

    name: Build Container
    runs-on: ubuntu-latest
    steps:
    
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Check out GitHub Repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CONTAINER_USER_NAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Push container to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_OWNER }}.azurecr.io/${{env.IMAGE_NAME}}:${{ env.RELEASE_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

    - name: Set environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azure-github-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        images: ${{ env.REGISTRY_OWNER }}.azurecr.io/${{env.IMAGE_NAME}}:${{ env.RELEASE_VERSION }}



  

