# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azure-github-container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://githubaction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9c452e11298a4837bf2745b328c516fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e08bf4bf2ddd41d49f3de1b5c915da65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: githubaction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9c452e11298a4837bf2745b328c516fb }}/githubaction/azure-hello-world-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azure-github-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bdd684a410ce405aa2a6758db2394dc5 }}
        images: 'githubaction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9c452e11298a4837bf2745b328c516fb }}/githubaction/azure-hello-world-app:${{ github.sha }}'